# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16liozXdHXclIYxjMQhny0u0f4ObWOQFL
"""

!pip install gradio plotly numpy scikit-learn -q

import numpy as np
import gradio as gr
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier

# ----------------------------
# Train Model
# ----------------------------
X = np.random.randint(50, 130, (200, 3))
y = ((X[:,0] > 100) | (X[:,1] < 90)).astype(int)

model = RandomForestClassifier()
model.fit(X, y)

# ----------------------------
# Drug Suggestion (Demo Only)
# ----------------------------
def suggest_drug(hr, spo2):
    if hr > 100:
        return "💊 Beta Blockers (for high heart rate)"
    elif spo2 < 90:
        return "💊 Oxygen Therapy / Respiratory Support"
    else:
        return "💊 No medication needed"

# ----------------------------
# Digital Twin Logic
# ----------------------------
def digital_twin(hr, spo2, motion):

    pred = model.predict([[hr, spo2, motion]])[0]
    status = "🟢 Normal" if pred == 0 else "🔴 Risk Detected"

    future = "⚠️ High future risk" if hr > 105 or spo2 < 88 else "✅ Stable future"

    drug = suggest_drug(hr, spo2)

    # ----------------------------
    # HUMAN BODY VISUAL
    # ----------------------------
    if pred == 1:
        body_color = "🔴"
        body_status = "Body Condition: Risk"
    else:
        body_color = "🟢"
        body_status = "Body Condition: Normal"

    body_visual = f"""
    ## 🧍 Human Digital Twin

    {body_color}
    {body_status}
    """

    # ----------------------------
    # VISUAL HEALTH GAUGE (NEW)
    # ----------------------------
    # import plotly.graph_objects as go # This is already imported globally at the top

    condition_value = 1 if pred == 1 else 0

    fig = go.Figure(go.Indicator(
        mode="gauge+number+delta",
        value=condition_value,

        title={'text': "Health Condition"},

        gauge={
            'axis': {'range': [0, 1]},

            'bar': {'color': "red" if pred == 1 else "green"},

            'steps': [
                {'range': [0, 0.5], 'color': "green"},
                {'range': [0.5, 1], 'color': "red"}
            ],

            'threshold': {
                'line': {'color': "white", 'width': 4},
                'thickness': 0.75,
                'value': condition_value
            }
        }
    ))

    fig.update_layout(template="plotly_dark")

    # Heart animation (simple)
    heart_icon = "❤️" if hr < 100 else "💔"

    # BIG OUTPUT TEXT
    output = f"""
# 🧍 DIGITAL TWIN HEALTH REPORT

## {heart_icon} Heart Rate: {hr}
## 🫁 SpO2 Level: {spo2}
## 🏃 Motion: {motion}

---

## 📊 CURRENT STATUS:
### {status}

## 🔮 FUTURE PREDICTION:
### {future}

## 💊 SUGGESTED ACTION:
### {drug}

---

⚠️ *This is a demo model. Not for real medical use.*
"""

    return output + body_visual, fig

# ----------------------------
# Voice Assistant Logic
# ----------------------------
def voice_input(audio):
    return "🎤 Voice received! (Demo: speech-to-text can be added)"

# ----------------------------
# UI (PROFESSIONAL BIG SCREEN)
# ----------------------------
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🧠 DIGITAL TWIN OF HUMAN")
    gr.Markdown("### AI-Based Health Monitoring & Prediction System")

    gr.Markdown("""
    ### 📡 System Flow

    Sensors ➝ AI Model ➝ Digital Twin ➝ Prediction

    - ECG / SpO2 / Motion Sensors
    - Machine Learning Processing
    - Virtual Human Model
    - Health Risk Prediction
    """)
    with gr.Row():
        with gr.Column(scale=1):
            hr = gr.Slider(50,130,label="❤️ Heart Rate")
            spo2 = gr.Slider(80,100,label="🫁 SpO2")
            motion = gr.Slider(0,10,label="🏃 Motion")

            btn = gr.Button("🚀 Run Digital Twin")

            gr.Markdown("### 🎤 Voice Input (Demo)")
            audio = gr.Audio(sources=["microphone"], type="filepath")
            voice_btn = gr.Button("Use Voice")

        with gr.Column(scale=2):
            output = gr.Markdown()
            graph = gr.Plot()

    btn.click(fn=digital_twin, inputs=[hr, spo2, motion], outputs=[output, graph])
    voice_btn.click(fn=voice_input, inputs=audio, outputs=output)

demo.launch()

